### ISSUE TITLE
Page you are brought to from "Character Wizard" does not have side navigation menu

### ISSUE THREAD

**Issue by AdiraSlat** [ask-again-later/character-system#101]
Chrome, Macbook Air

After clicking "Character wizard," I was brought to http://aal-character-system-staging.herokuapp.com/characters/wizard

![screen shot 2017-03-31 at 10 53 50 am](https://cloud.githubusercontent.com/assets/16806155/24558324/595bf2b8-1600-11e7-8127-a3e6639eb4c8.png)

My assumption is that it would look like this:

![screen shot 2017-03-31 at 10 51 17 am](https://cloud.githubusercontent.com/assets/16806155/24558333/61ddd7da-1600-11e7-9d94-68fe8cb3a596.png)

**Comment by sublimemarch** [comment]
This behavior is intentional.
