### ISSUE TITLE
Advantages: need description of Drain, Dread Attack (maybe Allies & Resources)

### ISSUE THREAD

**Issue by isajanusz** [ask-again-later/character-system#106]
When you click to edit Drain and Dread Attack, they say "This is a description of Drain" and "This is a description of Dread Attacks," respectively. Allies and Resources say "How much money, yo" and "Your friends yo," respectively, but I wasn't sure if that was a placeholder or you wanted that there because we are Fun and Fresh.

**Comment by sublimemarch** [comment]
These are placeholders for now, the actual Advantages haven't been entered into the system. Thank you for the thorough bugs! 👯
