### ISSUE TITLE
Can't click "My Characters" in navbar to go to characters/index

### ISSUE THREAD

**Issue by sublimemarch** [ask-again-later/character-system#118]

**Comment by korey-enright** [comment]
This isn't a mobile only thing, how do we want to solve it - right now my characters is a drop down menu to select a character from available characters. Should mobile users have to double tap? Should they have a "return to characters index" option? Right now the only way to get back to the character index on the navbar is to click AAL.

**Comment by carlydotwebsite** [comment]
I'd say change it to a link rather than a span? But yeah, it's kind of tricky on mobile. I might just auto-expand the dropdown on mobile since most people won't have a very long characters list.
