### ISSUE TITLE
Need to display bullets on bulleted lists for certain items

### ISSUE THREAD

**Issue by carlydotwebsite** [ask-again-later/character-system#146]
We need to be able to display the bullets for bulleted lists for the descriptions of advantages, challenges, etc.; I think they're being removed by the reset stylesheet.

**Comment by korey-enright** [comment]
that they are. as a note, we have to manually set up the nested list styles, so I'm not sure how deep we want to go with that.

**Comment by carlydotwebsite** [comment]
I don't think we need to go particularly deep on that. It's unlikely we're going to see more than one level, but I'd go to three? Circle, disc, square?

**Comment by korey-enright** [comment]
sounds good to me! we should do the same with ordered lists, if they're not working
