### ISSUE TITLE
Styling for stability boxes for character/show

### ISSUE THREAD

**Issue by sublimemarch** [ask-again-later/character-system#39]
Stability boxes should be starbursts, a single box is filled in.
Seven boxes. Box that is filled in is a bit bigger and has the number inside it.

**Comment by sublimemarch** [comment]
The shape we discussed is something like this: http://www.clker.com/cliparts/P/R/M/d/7/q/starburst-outline-black.svg

**Comment by carlydotwebsite** [comment]
Shame there's no outline version of fa-certificate

-- 
Carly Ho
