### ISSUE TITLE
As a storyteller, I want to assign a status to player characters.

### ISSUE THREAD

**Issue by sublimemarch** [ask-again-later/character-system#58]
Statuses:

In Progress
Approved
Declined
Revisions Requested

**Comment by sublimemarch** [comment]
Does this already exist?

**Comment by carlydotwebsite** [comment]
This already exists, although the status names are somewhat different—currently we have "In Progress", "Submitted", "Active" and "Inactive." Do we still want to add "Revisions Requested" and "Declined"?

**Comment by sublimemarch** [comment]
Hmmm... I think we don't need "Declined." Any characters we don't approve can just be marked as "Inactive."

If we request revisions, would we just send the character back to "In Progress"? I think that would make sense.

**Comment by carlydotwebsite** [comment]
Yeah, I think just moving it back to "in progress" makes sense.

**Comment by sublimemarch** [comment]
Sounds good! I'll close this issue. Let's make sure to create documentation for the rest of the ST team that makes the statuses clear.
