### ISSUE TITLE
As a storyteller, I want to be able to manage characters. 

### ISSUE THREAD

**Issue by sublimemarch** [ask-again-later/character-system#61]
This includes things like:

- viewing characters
- moving them through an approval process
- editing them before approval
- editing them after approval

**Comment by sublimemarch** [comment]
I think most of this exists? Can someone confirm?

**Comment by carlydotwebsite** [comment]
Some of it exists; Storytellers get an extra dropdown that allows them to change a character's status. We haven't yet implemented parts that stop _non_-storytellers from editing sheets after they've been submitted, or that remove the edit links for non-storytellers after they've been submitted.

**Comment by sublimemarch** [comment]
Sounds good! I've made new issues for these: #70 and #71

Closing this issue, then. Thanks!
