### ISSUE TITLE
As a storyteller, I want to make NPC characters.

### ISSUE THREAD

**Issue by sublimemarch** [ask-again-later/character-system#64]
Such as:

- checkbox for STs to make a character an NPC
- only print fields that aren't zero/empty
- text boxes for additional info
- box for motivation, etc
- filter NPCs as separate from PCs for printing, viewing, etc

**Comment by carlydotwebsite** [comment]
Notes to self for implementation:

* Create separate form for creating NPCs (add a button on ST root path to go to this page?)
* NPCs default to "active", mark as "inactive" to not print (in-progress/submitted not really a thing for them)
* Exclude NPCs from characters API
* Separate route for printing active NPCs
* Add motivation (alt: repurpose public_blurb for NPCs?)
* Probably need at least one additional information text box that's only used for NPCs, though.
