### ISSUE TITLE
Downtime processing system

### ISSUE THREAD

**Issue by sublimemarch** [ask-again-later/character-system#65]
Details of downtime system should be filled in here.

**Comment by carlydotwebsite** [comment]
Downtime system requirements/implementation suggestions:

* A Character has_many DowntimeActions; a DowntimeAction belongs_to Character
* Also suggest we create additional model Game, which has t.integer :id, t.string :name, t.boolean :responses_visible and has_many DowntimeActions
* DowntimeAction fields: t.integer :character_id, t.string :title, t.string :assets, t.text :description, t.integer :downtime_type, t.boolean :burn, t.text :response, t.integer :game_id
* Add a link in the characters list table next to a character record that says "Downtime Actions" that allows players to go to route /characters/:id/downtime_actions
* Player may save a downtime action before submitting it for purposes of drafting it
* Have help text for certain fields (e.g. for assets, mention that players should list any helpers they have; for description, note that it should be ~4 sentences [unless you are burning down your life, in which case you are allowed like 8? haha])
* Once a player submits a downtime action (distinct from saving), an email is generated to the STs with the content of the downtime
* The STs, viewing a submitted downtime action, can enter a response in the :response field that contains the results of the downtime action. The player cannot see the response until the Game it belongs to is marked :responses_visible to prevent some players from getting their responses earlier.
* The STs should also have a route that allows them to print all the downtime responses for a single game, organized by character. (/storytellers/downtimes/:game_id/print_all ?)
