### ISSUE TITLE
Send an email to player when character is approved

### ISSUE THREAD

**Issue by sublimemarch** [ask-again-later/character-system#68]

**Comment by carlydotwebsite** [comment]
Potential implementation notes:

* Add flag to characters that tracks whether they've received their approval email
* Add storyteller button that batch sends approvals to anyone who is marked as "active" (status = 2) and doesn't have that flag and is not marked as an NPC 

(Do we want to batch send denials, too? We might need to add a separate status for that.)

**Comment by sublimemarch** [comment]
Re: batch denials: Hmm, I suppose it's a matter of how we want to deal with denials, and if we'd rather send a form email or something that feels more kind. Let's worry about that in a separate issue for a future deployment though. 😄
