### ISSUE TITLE
Add Markdown parsing for printed descriptions

### ISSUE THREAD

**Issue by carlydotwebsite** [ask-again-later/character-system#74]
Need to add a RedCarpet wrapper around descriptions printed for Advantages and Challenges on characters/_form; also need to add a javascript markdown parser to handle descriptions inserted via AJAX or entered in the "new challenge" box.

**Comment by sublimemarch** [comment]
Just to clarify, this should apply to characters/_form, characters/show, and the print version of a character?

**Comment by carlydotwebsite** [comment]
Yeah, it should apply to all three of those. I think it's all implemented on characters/show, but not entirely on characters/_form and I don't think at all on the print version.

**Comment by carlydotwebsite** [comment]
note to self: https://github.com/joshmcarthur/showdown-rails
