### ISSUE TITLE
Add styling for "Remember me" label so it's inline with checkbox

### ISSUE THREAD

**Issue by carlydotwebsite** [ask-again-later/character-system#75]
![screen shot 2017-03-27 at 1 12 38 pm](https://cloud.githubusercontent.com/assets/267841/24371103/657196de-12ef-11e7-8e6c-9b0395e18a00.png)

**Comment by sublimemarch** [comment]
I'm going to scoot this to Release #2, as it's a bug that needs to be fixed before we release to players, but not before we allow QA testers in.
