### ISSUE TITLE
On log in, spacing of "Remember Me"

### ISSUE THREAD

**Issue by isajanusz** [ask-again-later/character-system#90]
I think the "in" in "Log in" should be capitalized, just for aesthetic reasons. Also the "Remember me" and box for it is weirdly stretched out across the log in box.

Device: Windows computer
Browser: Chrome
Size: doesn't matter if it's full-screen or smaller
Screenshot: 
![weird spacing](https://cloud.githubusercontent.com/assets/26777208/24475039/514c5a6c-1494-11e7-940f-a885a16a65f0.PNG)

(Edit) also looks the same on iPhone:
![img_0260](https://cloud.githubusercontent.com/assets/26777208/24476331/889bfc62-1498-11e7-926d-1066a070534c.PNG)

**Comment by sublimemarch** [comment]
I'm going to split the capitalization of "Log in" to a separate ticket so we can track it better. 😄 

This has been separated out into #91
