### ISSUE TITLE
Sign up doesn't require email ending in email address

### ISSUE THREAD

**Issue by isajanusz** [ask-again-later/character-system#92]
I don't know if it just fills it in with ".com" if you leave it out, but when making a new account, I was allowed to make my sign-up email "test@gmail"

**Comment by carlydotwebsite** [comment]
@ code team—how do we want to handle validation for this? I guess we could validate email on a regular expression that just requires the dot (since some of us even own domains on goofy TLDs like .party and .website)

**Comment by sublimemarch** [comment]
Change it to input email

**Comment by korey-enright** [comment]
It's already an email input, and the validations work appropriately to the extent that it is possible to validate.
```something@gmail``` isn't valid, theoretically, but ```something@localserver``` or ```something@com``` or ```something@[IPv6:2001:db8::1]```  is valid, so emails don't necessarily need a dot.

**Comment by carlydotwebsite** [comment]
Hm, yeah, it's kind of difficult to validate an email address at all, apparently, without having a super long regular expression. I'm not expecting many people to try and enter their email like name@gmail, but if they do, we can change their email in the database, I guess?

**Comment by korey-enright** [comment]
yeah, the super long regex is built into the browsers and allows for all potentially valid emails, the only other thing would be correcting incorrect suffixes but that's.... not a good solution
