### ISSUE TITLE
Attempting to finish a blank Character Wizard mechanics character gives a blank page

### ISSUE THREAD

**Issue by AdiraSlat** [ask-again-later/character-system#97]
Chrome, Macbook Air

I entered in "hhhhhhh" as the name and as every value in the first page of questions, and then I clicked save. I then clicked "save and next page" on the bottom for each one, and then clicked finished. It brought me to a blank page. Refreshing the page "fixed" it, replacing it with an uneditable overview of the character sheet.

**Comment by sublimemarch** [comment]
@MarkSlat What's the link of the URL it took you to? Also, did the blank page show the navbar?

**Comment by AdiraSlat** [comment]
The blank page did not show the navbar. The url it took me to was http://aal-character-system-staging.herokuapp.com/characters/4/
