### ISSUE TITLE
Clicking "New Character" brings me to that page where I can't submit questionnaire answers

### ISSUE THREAD

**Issue by AdiraSlat** [ask-again-later/character-system#98]
Chrome, Macbook Air

Clicking the button labeled "New Character" brings me to a page that looks to be the "skip to the full mechanical build" option, but at the bottom of the sheet I cannot answer any of the questionnaire.  Only the question group subtitles are displayed. The cursor changes like I can click the subtitles, but I am unable to click them.

http://aal-character-system-staging.herokuapp.com/characters/new

![screen shot 2017-03-31 at 10 34 38 am](https://cloud.githubusercontent.com/assets/16806155/24557548/b2c57390-15fd-11e7-99c1-0990778a00bc.png)
![screen shot 2017-03-31 at 10 34 50 am](https://cloud.githubusercontent.com/assets/16806155/24557547/b2c674ac-15fd-11e7-8640-aa94d90c38a0.png)

**Comment by sublimemarch** [comment]
@MarkSlat can we get a screenshot of what that new page looks like and its URL? Thanks!

**Comment by AdiraSlat** [comment]
Those are two screenshots, one of the top of the page and one of the bottom of the page where you are unable to answer the questionnaire
