### ISSUE TITLE
"Character Wizard" and "New Character" button is redundant

### ISSUE THREAD

**Issue by AdiraSlat** [ask-again-later/character-system#99]
Chrome, Macbook Air

This is on the home page after logging in. There should just be one button that brings you all to one place. It should be the page where "Character Wizard" leads now.

http://aal-character-system-staging.herokuapp.com/
![screen shot 2017-03-31 at 10 36 25 am](https://cloud.githubusercontent.com/assets/16806155/24557623/ecfcd3b4-15fd-11e7-9105-eda8cda10600.png)

**Comment by sublimemarch** [comment]
@MarkSlat On what page are you seeing these two buttons? Screenshot and URL are helpful. :)
